# kubeadm-join.yml
---
- hosts: kubenodes
  become: true

  tasks:
    - name: join kubemaster
    
    this task needs to be automatized!
      command: kubeadm join 172.31.37.252:6443 --token 7qrd6k.wd708ewbipzicb5k --discovery-token-ca-cert-hash sha256:275ee4311de682093edfdd242bc4db772ada986646f0207a28d71a6391ab24d6