# pod-network-init.yml
---
- hosts: kubemaster
  become: true

  tasks:
    - name: initialize pod network
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU
